[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# Align with Lambda runtime (python3.11)
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.67",
]
