[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# Align with Lambda runtime (python3.11)
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.25.1",
    "boto3>=1.42.5",
]
