---
on:
    workflow_dispatch:

jobs:
    iac:
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  allow-no-subscriptions: true
            - name: deploy-aws-identity-pool
              uses: aws-actions/aws-cloudformation-github-deploy@v1
              with:
                  name: infra-stack
                  template: infra/aws/IdentityPool.yaml
                  no-fail-on-empty-changeset: true
            - name: deploy-azure-resources
              uses: azure/bicep-deploy@v2
              with:
                name: 'Azure Workload Identity'
                type: 'deployment'
                operation: 'create'
                scope: 'resourceGroup'
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
                template-file: infra/azure/main.bicep
                parameters: |
                  oidcAudience=${{ steps.deploy-aws-identity-pool.outputs.IdentityPoolId }}
                  developerProvidedName=${{ steps.deploy-aws-identity-pool.outputs.DeveloperProviderName }}